
  // src/app/Enums/report-request-type.enum.ts
export enum ReportRequestType {
  READING_UNIT_CONSUMED_FAULT = 'READING_UNIT_CONSUMED_FAULT',
  NAME_CHANGE = 'NAME_CHANGE',
  EMAIL_CHANGE = 'EMAIL_CHANGE',
  ADDRESS_CHANGE = 'ADDRESS_CHANGE',
  PHONE_CHANGE = 'PHONE_CHANGE',
  EXTEND_DUE_DATE = 'EXTEND_DUE_DATE',
  BILL_WAIVE_OFF = 'BILL_WAIVE_OFF',
}
